###
GET http://127.0.0.1:3000/tasks

###
GET http://127.0.0.1:3000/tasks
User-Id: 2

###
POST http://127.0.0.1:3000/tasks
Content-Type: application/json
User-Id: 1

{"title": "Сделать тест"}

###
POST http://127.0.0.1:3000/tasks
Content-Type: application/json
User-Id: 1

{}

###
GET http://127.0.0.1:3000/tasks/6
User-Id: 1

###
GET http://127.0.0.1:3000/tasks/6
User-Id: 2

###
GET http://127.0.0.1:3000/tasks/7
User-Id: 1

###
PATCH http://127.0.0.1:3000/tasks/6
Content-Type: application/json
User-Id: 1

{}

###
PATCH http://127.0.0.1:3000/tasks/6
Content-Type: application/json
User-Id: 1

{"title": "Убрать тест"}

###
PATCH http://127.0.0.1:3000/tasks/7
Content-Type: application/json
User-Id: 1

{"title": "Убрать тест"}

###
DELETE http://127.0.0.1:3000/tasks/7
User-Id: 1

###
DELETE http://127.0.0.1:3000/tasks/5
User-Id: 1

###
GET http://127.0.0.1:3000/tasks
User-Id: 1

###
GET http://127.0.0.1:3000/users

###
POST http://127.0.0.1:3000/users
Content-Type: application/json

{"name": "Тестович"}

###
POST http://127.0.0.1:3000/users
Content-Type: application/json

{}

###
GET http://127.0.0.1:3000/users/2

###
GET http://127.0.0.1:3000/users/3

###
PATCH http://127.0.0.1:3000/users/2
Content-Type: application/json

{}

###
PATCH http://127.0.0.1:3000/users/2
Content-Type: application/json

{"name": "Тестовна"}

###
DELETE http://127.0.0.1:3000/users/3

###
DELETE http://127.0.0.1:3000/users/2

###
GET http://127.0.0.1:3000/users
